### ISSUE TITLE
✨ feat: configurar integração de components do Preline com Next.js 15 no design system nextime-ui

### ISSUE THREAD

**Issue by nextimecode** [nextimecode/stark#10]
#### **Contexto**
O design system `nextime-ui` deve ser expandido para suportar os componentes da biblioteca Preline de forma integrada com projetos baseados em Next.js 15. Isso garantirá que os desenvolvedores possam utilizar os componentes através de uma instalação simples da lib `@nextime-ui/react`, mantendo consistência de design e eficiência no desenvolvimento.

---

#### **Tipo de Card**
História

**Motivo:** Representa uma funcionalidade que adicionará valor direto aos usuários do design system.

---

#### **Descrição Detalhada**
1. Configurar o suporte à biblioteca Preline dentro do `nextime-ui`.
2. Integrar os estilos e comportamentos dos componentes com o Next.js 15.
3. Garantir que a instalação e o uso sejam simples ao importar `@nextime-ui/react` no projeto.
4. Documentar como utilizar os componentes em projetos Next.js 15.
5. Criar testes básicos para validar a funcionalidade dos componentes no Next.js.

---

#### **Critérios de Aceitação**
- [ ] Os componentes Preline podem ser utilizados diretamente a partir do pacote `@nextime-ui/react`.
- [ ] A integração funciona perfeitamente em projetos baseados no Next.js 15.
- [ ] A documentação cobre:
  - Instalação e configuração inicial.
  - Exemplos práticos de uso no Next.js.
- [ ] Testes automatizados validam a funcionalidade dos componentes integrados.

---

#### **Links ou Referências Úteis**
- [[Documentação do Preline](https://preline.io/)](https://preline.io)
- [[Documentação do Next.js 15](https://nextjs.org/docs)](https://nextjs.org/docs)
- [[Repositório do Nextime UI](https://github.com/nextimecode/nextime-ui)](https://github.com/nextimecode/nextime-ui)

---

#### **Estimativa de Esforço**
**8 horas**  
Tarefa de nível médio considerando a familiaridade com Preline, Next.js, e configuração de pacotes no monorepo.

---

#### **Requisitos**
**Funcionais**
- Suporte aos estilos e comportamentos dos componentes do Preline.
- Integração simplificada com projetos Next.js.

**Não Funcionais**
- Documentação e exemplos acessíveis.
- Código modular e testado.

**Regras de Negócio**
- Apenas componentes compatíveis devem ser adicionados à lib.

---

#### **Checklist**
- [ ] Configurar suporte aos componentes do Preline.
- [ ] Criar exemplos de integração no Next.js 15.
- [ ] Escrever testes automatizados.
- [ ] Documentar a funcionalidade no repositório.
- [ ] Validar a implementação com um projeto Next.js real.

**Comment by phdduarte** [comment]
Consegui configurar a lib, agora falta criar o componetne button com as tipagens do preline e testar no projeto
