### ISSUE TITLE
🔄 ci: configurar pipelines de ci/cd para preview e produção nos apps do projeto

### ISSUE THREAD

**Issue by nextimecode** [nextimecode/stark#8]
🔄 ci: configurar pipelines de ci/cd para preview e produção nos apps do projeto

### **Contexto:**  
O projeto Stark precisa de uma pipeline automatizada de CI/CD para gerenciar e validar o fluxo de desenvolvimento, preview e produção nos três apps do monorepo: Arya, Bran e Sansa. Essa configuração deve incluir lint, typecheck, testes E2E, e deploy automatizado para garantir a qualidade e eficiência nas entregas.

### **Tipo de Card:**  
Tarefa

### **Descrição Detalhada:**  
Implementar e configurar pipelines utilizando GitHub Actions para atender aos seguintes fluxos:  
1. **Preview**:
   - Gatilho para pull requests na branch `main`.
   - Execução de:
     - Lint.
     - Typecheck.
     - Auditoria de dependências (`pnpm audit`).
     - Testes E2E.
   - Deploy automatizado para um ambiente de preview após validação.

2. **Produção**:
   - Gatilho para push na branch `main`.
   - Execução completa de validações (lint, typecheck, audit, testes E2E).
   - Deploy automatizado para o ambiente de produção.

3. **Testes Pós-Deploy**:
   - Automatizar execução de testes E2E após o deploy (em preview e produção).

4. **Releases**:
   - Configurar processo para publicação de pacotes no npm quando aplicável.

### **Critérios de Aceitação:**  
- [ ] Configurar pipelines de CI/CD para preview e produção nos três apps (`Arya`, `Bran`, `Sansa`).
- [ ] Garantir que os passos de lint, typecheck e testes automatizados sejam executados em cada fluxo.
- [ ] Deploy para preview configurado em pull requests.
- [ ] Deploy para produção configurado em push na branch `main`.
- [ ] Execução de testes E2E automática após deploy.
- [ ] Utilizar workflows reutilizáveis onde possível (e.g., `action.yml`).
- [ ] Documentação clara sobre os fluxos configurados.

### **Links ou Referências Úteis:**  
- [[GitHub Actions Documentation](https://docs.github.com/actions)](https://docs.github.com/actions)
- [[Playwright E2E Testing](https://playwright.dev/)](https://playwright.dev/)
- Exemplos: `preview.yml`, `release.yml`, e `run-e2e.yml`.

### **Estimativa de Esforço:**  
8-10 horas.

### **Requisitos Funcionais:**  
- Configuração de pipelines para automação de deploys e validações em cada fluxo.
- Execução automatizada de testes E2E e relatórios.

### **Requisitos Não Funcionais:**  
- As pipelines devem ser eficientes e otimizadas, reduzindo o tempo de execução ao máximo.
- Reutilizar componentes ou workflows genéricos para evitar duplicação de código.

### **Checklist:**  
- [ ] Configurar fluxo de `preview` para pull requests.
- [ ] Configurar fluxo de `production` para push na branch `main`.
- [ ] Adicionar execução de testes E2E pós-deploy.
- [ ] Validar o funcionamento completo da pipeline.
- [ ] Documentar o processo no repositório para futuros mantenedores.

**Comment by phdduarte** [comment]
api bran 
https://api.nextime.com.br/

portal arya 
https://teste.nextime.com.br/
ou 
https://test.nextime.com.br/

e parte logada 
https://app.nextime.com.br/
